// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNqPGXZqs3sc8zA08zKS_7MMYfS1vLe-8',
    appId: '1:261356115874:web:736444a0f8dc444c8fc4fb',
    messagingSenderId: '261356115874',
    projectId: 'bmii-83422',
    authDomain: 'bmii-83422.firebaseapp.com',
    storageBucket: 'bmii-83422.appspot.com',
    measurementId: 'G-Q08NWF6V80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Htx20byoj9U42zNiCfQ3J1UKLOVg6ws',
    appId: '1:261356115874:android:46e2212e8a0b3ca98fc4fb',
    messagingSenderId: '261356115874',
    projectId: 'bmii-83422',
    storageBucket: 'bmii-83422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA36XgREcrUSZVMbGLoT8vNNaeu6wNezPo',
    appId: '1:261356115874:ios:d190d90c89fe0e3e8fc4fb',
    messagingSenderId: '261356115874',
    projectId: 'bmii-83422',
    storageBucket: 'bmii-83422.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA36XgREcrUSZVMbGLoT8vNNaeu6wNezPo',
    appId: '1:261356115874:ios:d190d90c89fe0e3e8fc4fb',
    messagingSenderId: '261356115874',
    projectId: 'bmii-83422',
    storageBucket: 'bmii-83422.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNqPGXZqs3sc8zA08zKS_7MMYfS1vLe-8',
    appId: '1:261356115874:web:89f24b8054e9a2ba8fc4fb',
    messagingSenderId: '261356115874',
    projectId: 'bmii-83422',
    authDomain: 'bmii-83422.firebaseapp.com',
    storageBucket: 'bmii-83422.appspot.com',
    measurementId: 'G-HBPJR4R4W3',
  );
}
